### ISSUE TITLE
Connect to DB

### ISSUE THREAD

**Issue by berlinum** [berlinum/bricks#7]
# User Story

As a user, I want to create a personal account so that all my data would by saved safe and independent from the app.

# To Do

* [x] Install mongoose
* [x] Create .env file with environment variables
* [x] Connect to Mongo DB using auth key from .env and mongoose
* [x] Create a User Model

**Comment by marwinburesch** [comment]
I'd say this is not just in the interest of the user, but also for developers or site-maintainers. Also you could split this up in several stories, which might make the development process a bit easier

In general I'd say users are only interested in back-end realted things when it come to securing their personal data.

What about this: 
As a user I want to be able to create a profile, so I can have a personalised experience
As a user I want that my data is stored independently from the app, so it is more secure
As a site-maintainer I want user data to be stored according to a schema, so that the database is easier to maintain and less prone to errors
